sudo: required 
services:
  - docker 

before_install:
  - docker build -t carlsongould/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carlsongould/docker-react npm run test

language: generic 
